controller_list:
  - name: fake_panda_1_controller
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  - name: fake_panda_2_controller
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
  - name: fake_hand_1_controller
    joints:
      - panda_1_finger_joint1
  - name: fake_hand_closed_chain_controller
    joints:
      - panda_1_finger_joint1
      - panda_3_finger_joint1
  - name: fake_panda_3_controller
    joints:
      - panda_3_joint1
      - panda_3_joint2
      - panda_3_joint3
      - panda_3_joint4
      - panda_3_joint5
      - panda_3_joint6
      - panda_3_joint7
  - name: fake_panda_closed_chain_controller
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
      - panda_3_joint1
      - panda_3_joint2
      - panda_3_joint3
      - panda_3_joint4
      - panda_3_joint5
      - panda_3_joint6
      - panda_3_joint7
  - name: fake_hand_2_controller
    joints:
      - panda_2_finger_joint1
  - name: fake_hand_3_controller
    joints:
      - panda_3_finger_joint1
  - name: fake_panda_chair_up_controller
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
      - panda_3_joint1
      - panda_3_joint2
      - panda_3_joint3
      - panda_3_joint4
      - panda_3_joint5
      - panda_3_joint6
      - panda_3_joint7
  - name: fake_hand_chair_up_controller
    joints:
      - panda_2_finger_joint1
      - panda_3_finger_joint1